# Generated by Django 3.2.8 on 2021-11-30 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usefulModels', '0006_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(help_text='Nội dung bình luận'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name_read',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='usefulModels.readingbook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='note',
            field=models.TextField(help_text='Nội dung cần ghi nhớ !'),
        ),
    ]
