# Generated by Django 3.2.8 on 2021-12-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usefulModels', '0007_auto_20211130_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary', models.CharField(max_length=20)),
                ('translate', models.CharField(max_length=100, null=True)),
                ('name_read', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usefulModels.readingbook')),
            ],
        ),
    ]
